# ==========================================
# 1. CORE SETTINGS
# ==========================================
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g mouse on
set-option -g allow-rename on
set-window-option -g automatic-rename on

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set-option -g default-shell /usr/bin/zsh

# ==========================================
# 2. VIM-MODE & COPY-PASTE
# ==========================================
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -i"

# ==========================================
# 3. PLUGINS (TPM)
# ==========================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# ==========================================
# 4. INITIALIZATION
# ==========================================
run '~/.tmux/plugins/tpm/tpm'
